version: 0.2
phases:
  pre_build:
    commands:
      - echo Instalando dependencias
      - npm install
  build:
     commands:
     - echp Build iniciando em 'date'
     - npm run build
  post_build:
    commands:
      - echo Build finalizando em 'date'
artifacts:
  files:
    - build/**/* 
    - Scriptsbuild/**/*
    - appspec.yml